#xray配置
xray:
        #扫描结果存储路径
        file_path: 
        
        #xray文件位置,不填则为默认路径
        xray_file_path:
        
        #xray 结果输出方式默认是 html|xray输入出方式仅有html,json,text
        input_file_type: 

#fofa配置
fofa:
        #fofa cookie
        Fofa_Cookie: 

        #fofa登录邮箱
        Fofa_email:  

        #fofa key值
        Fofa_key:

        #fofa搜索语法,可直接在后面添加
        fofaQuerysyntax:
                - status_code=200



#全局配置
global:
        #是否开启fofa爬虫模式,开启后需填写Fofa_Cookie和fofaQuery(开启后将不会使用fofaAPI,fofa高级会员勿用)
        fofareptile: no
        
        #是否只扫描域名,如果需要请修改为yes
        scan_domain_name: no

        #多线程数量
        threads: 5
        
